auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: I¡¯m here. I'm Doxie.
url: http://dz9.github.io
feed: /atom.xml
author_info: <a href="http://dz9.github.io/">Doxie</a>
